require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-rake

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes